# Site settings
title: 雪碧有点甜的博客
SEOTitle: 雪碧有点甜的博客
header-img: img/post-bg-rwd.jpg
email: xingboplus@gmail.com
description: "日常开发总结和生活感悟"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://happyxb.github.io" # the base hostname & protocol for your site
keyword: iOS,雪碧有点甜的博客
github_username:  happyxb

# Build settings
markdown: kramdown
